export default () => ({
    items: [
        {
            id:1, jenis_tes:'Pemeriksaan Darah Rutin',img:'tes_darah.jpg', harga:'50000',lama_periksa:'15 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:2, jenis_tes:'Hemoglobin',img:'hemoglobin.jpeg', harga:'50000',lama_periksa:'15 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Hemoglobin merupakan komponen utama sel darah Hemoglobin merupakan kompenon utama sel darah merah dan berfungsi untuk transport oksigen. Kekurangan hemoglobin pada darah akan menyebabkan penyakit Anemia. Anemia adalah suatu kondisi tubuh yang ditandai dengan hasil pemeriksaan kadar hemoglobin (Hb) dalam darah lebih rendah dari normal, yang bisa disebabkan jumlah sel darah merah yang kurang (contohnya pada perdarahan berat akibat kecelakaan, atau sebab lainnya), atau jumlah sel darah merah cukup tapi kandungan Hb didalam sel darah merah kurang'
        },
        {
            id:3, jenis_tes:'Glukosa Darah Sewaktu',img:'glukosa_darah.jpg', harga:'50000',lama_periksa:'15 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:4, jenis_tes:'Glukosa Darah Puasa',img:'glukosa_darah_puasa.jpg', harga:'50000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:5, jenis_tes:'Kolesterol',img:'kolesterol.png', harga:'50000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:6, jenis_tes:'Asam Urat',img:'asam_urat.png', harga:'30000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:7, jenis_tes:'hCG/Kehamilan',img:'kehamilan.png', harga:'20000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:8, jenis_tes:'Hepatitis B (HBsAg)',img:'hepatitis_b.png', harga:'20000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:9, jenis_tes:'Hepatitis C',img:'hepatitis_c.png', harga:'20000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:10, jenis_tes:'Sifilis',img:'sifilis.jpg', harga:'20000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:11, jenis_tes:'Anti HBS',img:'anti_hbs.jpg', harga:'20000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:12, jenis_tes:'Malaria',img:'malaria.png', harga:'20000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:13, jenis_tes:'DBD',img:'dbd.jpg', harga:'20000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:14, jenis_tes:'Typhoid',img:'typhoid.jpg', harga:'20000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:15, jenis_tes:'Golongan Darah',img:'golongan_darah.jpg', harga:'20000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:16, jenis_tes:'Antigen Covid 19',img:'antigen_covid.jpg', harga:'20000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:17, jenis_tes:'Urin Rutin',img:'tes-urine.png', harga:'20000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:18, jenis_tes:'Protein Urine',img:'protein_urine.jpg', harga:'20000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        },
        {
            id:19, jenis_tes:'Basil Tahan Asam',img:'basil_tahan_asam.jpg', harga:'20000',lama_periksa:'5 menit', manfaat:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores cumque minus asperiores, unde vero ipsa incidunt excepturi deleniti sunt saepe alias dicta repellat maiores, officiis delectus rem officia aperiam obcaecati.', persiapan:'tidak ada persiapan khusus',deskripsi:'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro! Vero atque nesciunt consectetur perspiciatis porro aliquid dolorem soluta laborum nisi tempora. Quisquam atque nostrum facilis accusamus iure quo, distinctio maiores excepturi repellendus. Enim earum saepe adipisci nostrum impedit alias at quos. In, saepe labore. At expedita maiores perferendis eius.'
        }
    ],
    selectedId : null

})

// //konversi ke rupiah 
// const rupiah = (number) => {
//     return new Intl.NumberFormat('id-ID', {
//        style : "currency",
//        currency : 'IDR',
//        minimumFractionDigits :0
//     }).format(number);
// }



